### ISSUE TITLE
The grand opening!

### ISSUE THREAD

**Issue by OleMchls** [hh-ex/planning#1]
We need to get started. I propose the last Tuesday each Month (for a start, might be discussed at the first meet up).

**Date:** February 23rd
**Agenda:**
- _TBD_

TODO:
- [ ] agenda
- [ ] create meet up on meetup.com 
- [ ] get the word out!
- [ ] invite Hamburg BEAMers

Thoughts @LydG ?

**Comment by OleMchls** [comment]
I think for the first meet up we will start with a easy agenda:
- Welcome
- Introduce the Organizers
- Get to know each other
- Collect ideas for talks and activities for following meet ups
- Hang out and have beers :beers:

**Comment by LydG** [comment]
![img_0327](https://cloud.githubusercontent.com/assets/16941601/13285452/f15376d2-dafa-11e5-825e-0ba9f33513ca.JPG)
![img_0328](https://cloud.githubusercontent.com/assets/16941601/13285451/f151e4c0-dafa-11e5-9395-5f1ff51651be.JPG)
![img_0329](https://cloud.githubusercontent.com/assets/16941601/13285453/f156e5ba-dafa-11e5-9071-78f6c9b81b82.JPG)
