### ISSUE TITLE
Tail Call optimization 

### ISSUE THREAD

**Issue by domenicolino** [hh-ex/planning#13]
I'm very new to the topic and for that reason I'd like to give a talk about tail call optimization. The idea is to learn by talking about it.
I'd like to make some benchmarks, understand what is the problem behind, and try to be able to explain it.

**Comment by h4cc** [comment]
This could lead to a matching coding kata on that topic.

**Comment by OleMchls** [comment]
@domenicolino I think this sounds like a great talk (format). We have the agenda already set for the May edition. And we also have two more proposals pending, so it could take a few more month to actually assign your talk to a month/edition.

@h4cc sure thing! you have something special in mind?

**Comment by OleMchls** [comment]
@domenicolino we are looking for a talk for #27 would you be in for that?

**Comment by OleMchls** [comment]
While still a great proposal, I consider the lack of activity as a withdrawal of the proposal.
