### ISSUE TITLE
July Edition

### ISSUE THREAD

**Issue by LydG** [hh-ex/planning#17]
- [x] Create meetup.com event
- [x] Agenda
- [ ] prepare katas if applicable
- [x] Location
- [ ] Announce meetup.com event (triggers mail)
- **Date:** July 26th
- **Location:** Jimdo

Agenda:
- 18:00 Open the doors 
- 18:30 Welcome 
- Talk: [Implementing binary protocols with Elixir](http://www.elixirconf.com/2016/speakers.html#michaelis) by @nesQuick
- [dtgcaa kata](https://github.com/hh-ex/kata-dtgcaa)
- Hang out and have beers, coke, mate or whats-o-ever 🍻

**Comment by OleMchls** [comment]
@LydG Jimdo is set this time?

**Comment by LydG** [comment]
Jepp it is. It is In the official calendar. 🎉

**Comment by OleMchls** [comment]
I already created the meetup event 👍

**Comment by h4cc** [comment]
I send the tweet: https://twitter.com/HamburgEx/status/746607276312657920

This should be at "june", sorry.

**Comment by OleMchls** [comment]
Awesome thanks! ❤️

**Comment by OleMchls** [comment]
As I will give a talk at Elixir Conf US at September 2nd and I won't be here for August edition I want to test drive my talk: [Implementing binary protocols with Elixir](http://www.elixirconf.com/2016/speakers.html#michaelis)

**Comment by h4cc** [comment]
Lets update meetup.com and announce?

http://www.meetup.com/de-DE/Elixir-Hamburg/events/232002451/

**Comment by OleMchls** [comment]
We'd need a 2nd agenda item, did we agree on the kata from @KlausTrainer ? My talk will be a bit longer (40 mins) I guess plus feedback I'd like to receive to a long kata might be a bit "too much"

opinions? @LydG @h4cc @KlausTrainer

**Comment by h4cc** [comment]
How about a "smaller" binary constructing/patternmatching kata?
Something more simple, like a very easy binary protocol send over UDP or something...

**Comment by OleMchls** [comment]
@h4cc Yeah, that'd be great. Would you prepare something? Or maybe just use the `binary rfc sigils tbd` I wanted to do anyway :)

We just added the details to meetup.com and it seems meet up automatically announces the UG :( Anyway, hopefully the great meet up details will reach everyone :)

I also announced it on twitter: https://twitter.com/HamburgEx/status/756428510806282240

**Comment by h4cc** [comment]
@nesQuick Like this? https://github.com/hh-ex/kata-binary

**Comment by OleMchls** [comment]
This is awesome. I love it. Thanks man!

**Comment by h4cc** [comment]
Do we have WiFi and Internet at the Location? People will need this to find binary Header Information.

I could prepare a short introduction to the kata.

**Comment by OleMchls** [comment]
We will have wifi. The task should be described in the readme. But you are very welcome to give a short introduction :)

**Comment by h4cc** [comment]
Added the wikipedia pages in `docs/`.
Added some hints in README.
Created a Pull-Request with the solution.
Added Travis-Ci.
