### ISSUE TITLE
August Edition

### ISSUE THREAD

**Issue by LydG** [hh-ex/planning#18]
- [x] Create meetup.com event
- [x] Agenda
- [ ] prepare katas if applicable
- [x] Location
- [ ] Announce meetup.com event (triggers mail)
- **Date:** August 30th
- **Location:** Jimdo

Agenda:
- 18:00 Open the doors 
- 18:30 Welcome 
- 19:00 Open Discussion
- Hang out and have beers, coke, mate or whats-o-ever 🍻

**Comment by OleMchls** [comment]
We might have a little problem here, neither me nor @LydG are available for the August meet up. Any takers? @h4cc @KlausTrainer :))

**Comment by h4cc** [comment]
You mean for Location or Moderation?

**Comment by OleMchls** [comment]
Taking general care of the meet up, we could organise it together, but we
are both out of town for the meet up. I'm sure we will find a location. We
have like ~4 default ones we can use :)

**Comment by OleMchls** [comment]
just secured Jimdo as location again <3 After Septembugers, Sabio already invited us, and I'd also love to hang out at Xing (@bjro) again :+1:

**Comment by OleMchls** [comment]
also just created the meetup.com event

**Comment by h4cc** [comment]
I think August should keep it low because of the Sommerloch, so we do not misspend one of the talks.
How about a simple meetup without a planned talk and more like a "bring your own topic"? + beer of course.

When Septemburger will be at Jimdo and after that SABIO has offered, how about Ubilabs?
@KlausTrainer Would that be ok to have August 30th at Ubilabs?

**Comment by h4cc** [comment]
Uhh, so Ubilabs can not host August meetup.
Any idea for a location other than Jimdo or Sabio?

**Comment by OleMchls** [comment]
Jimdo is already booked so why are you searching for a location? It was just a effort to help organising

**Comment by OleMchls** [comment]
> How about a simple meetup without a planned talk and more like a "bring your own topic"? + beer of course.

Would be fine for me. But that's a format which would need some more moderation. If that's fine for you, I'd just go and write the meetup description.

**Comment by h4cc** [comment]
Wrote the Meetup description. Going to announce tomorrow on meetup.com and twitter.

Still thinking if a small kata would fit....

**Comment by OleMchls** [comment]
Awesome, thanks for jumping in on this one! <3

**Comment by OleMchls** [comment]
I think a small kata might be fun!

**Comment by h4cc** [comment]
Announced!

**Comment by OleMchls** [comment]
awesome <3

**Comment by h4cc** [comment]
I am working on a small kata for GenServer that will hopefully bring a different perspective on working with processes.

**Comment by OleMchls** [comment]
Sweet! You could also just take one from the list in the kata issue, would
save some time. Just in case

**Comment by h4cc** [comment]
There is a kata for GenServers now: https://github.com/hh-ex/kata-genserver-basics
Hope it is not too much, it will be the second part of my topic for the "open discussion".
