### ISSUE TITLE
Build your own GenServer

### ISSUE THREAD

**Issue by BjRo** [hh-ex/planning#19]
...which is something you'd never ever want to try in the real world :-)

The basic idea of the talk would be to built an own (of course not feature complete) version of `GenServer` kinda from scratch. We would discover together why the GenServer API is structured the way it is. Once you understand the basics, in my opinion, everything falls nicely into place.

Could even have nice follow-up with "Build your own Supervisor" :-)

**Comment by BjRo** [comment]
@nesQuick Is it possible that you're the only one currently who can assign lables? Somehow the UI doesn't allow it for me currently...

**Comment by OleMchls** [comment]
@BjRo definitely possible, I changed some permissions now. can you please check again?

**Comment by BjRo** [comment]
@nesQuick Nope, still not working. I don't see the checkboxes in front of the issues in the overview.

**Comment by OleMchls** [comment]
@BjRo It's probably because you did not had write access to this repo. I created a `members` team granted you and @h4cc write access. So this should now really fixed it 👍

**Comment by OleMchls** [comment]
btw I really do like the talk!

**Comment by BjRo** [comment]
@nesQuick @h4cc 👍 Works like a charm. Thx!

**Comment by OleMchls** [comment]
While still a great proposal, I consider the lack of activity as a withdrawal of the proposal.
