### ISSUE TITLE
Septemburgers

### ISSUE THREAD

**Issue by OleMchls** [hh-ex/planning#22]
We want to do something different than talks and coding all the time, so let's have burgers together!

What needs doing?
- [x] Burger place
- [x] meetup.com event
- [x] should we charge to reduce no-show

**Comment by narrowtux** [comment]
Bürger Place suggestion:

PETER PANE Turnhalle Hamburg Burgergrill & Bar
Lange Reihe 107, 20099 Hamburg
040 28008535
https://goo.gl/maps/QcHgmLe8r2o

**Comment by OleMchls** [comment]
We'll be at Burger Lab, even tho they do not take reservations. We will just show up a bit earlier and make it work :D Also I created Meetup event and tweeted, as one does :D

**Comment by fsmanuel** [comment]
LGTM!

**Comment by h4cc** [comment]
Another tweet: https://twitter.com/HamburgEx/status/780290303651618816

**Comment by OleMchls** [comment]
well that was fun 🎉
