### ISSUE TITLE
meetup.com sponsorship

### ISSUE THREAD

**Issue by OleMchls** [hh-ex/planning#23]
Hey all,

We pay **$4.99/month** for meetup.com at the moment the costs are covered by me. But I wanted to see if we could find a official sponsor for that.
## What's in for your company?

All user group sponsor are listed on our official meetup.com page in the left side bar. Also I'd add a logo, link and note to the readme.md of this repo.

 🎉 ✨

**Comment by cnigischer** [comment]
Would the logo/link also be visible in the mobile app?

**Comment by OleMchls** [comment]
@cnigischer I don't really know because I do not use the mobile app. You could check the PHPHHUG group they have a few sponsors listed. If these appear in the mobile app as wel

**Comment by narrowtux** [comment]
@digimondo confirmed

**Comment by OleMchls** [comment]
@narrowtux that's great news! I'll check the next steps :)

**Comment by OleMchls** [comment]
@narrowtux I'd need the following to add it at meetup.com

```
You can upload a .jpg, .gif, or .png file. File size limit is 10 MB.
For best results make your photo 120 x 90. 
```

**Comment by narrowtux** [comment]
![logo_s](https://cloud.githubusercontent.com/assets/616791/21177795/fdf80d10-c1ec-11e6-8429-669fe04250fb.png)

**Comment by narrowtux** [comment]
120 x 90 px?

**Comment by narrowtux** [comment]
![image](https://cloud.githubusercontent.com/assets/616791/21177854/4361b356-c1ed-11e6-85a8-0ad3afbb2902.png)

I downscaled it for you

**Comment by OleMchls** [comment]
It's live! 
<img width="909" alt="screen shot 2016-12-14 at 11 07 59" src="https://cloud.githubusercontent.com/assets/584259/21177960/9f4b4ba0-c1ed-11e6-88f1-fb32d97efb11.png">

**Comment by OleMchls** [comment]
I'm in contact with meetup.com to organise the money part. I'll let you know once I figured it out 👍

**Comment by narrowtux** [comment]
Neat!

**Comment by narrowtux** [comment]
Sorry but I noticed that the logo is not crisp on Retina displays.

![image](https://cloud.githubusercontent.com/assets/616791/21178106/4ea899cc-c1ee-11e6-9e2f-1c56f241934b.png)

this one has double resolution can you see if that works?

**Comment by OleMchls** [comment]
I just replaced it, did not seem to work. Could you verify?

**Comment by narrowtux** [comment]
Yeah same here

**Comment by OleMchls** [comment]
This platform sucks. I'll open up a support request
