### ISSUE TITLE
Parsing formulas and reducing their AST

### ISSUE THREAD

**Issue by narrowtux** [hh-ex/planning#26]
I made a talk demonstrating the basics of my library @narrowtux/abacus at august edition and would like to show it again to a bigger audience. 

Topics:
- writing lexers with :leex 
- writing parsers with :yeec 
- reducing the syntax tree to the solution of the formula (and to other things)

**Comment by h4cc** [comment]
Aint that some nice elixir code? :)
https://github.com/narrowtux/abacus/blob/master/lib/eval.ex

**Comment by narrowtux** [comment]
Uploaded the deck on slidr https://slidr.io/narrowtux/how-to-parse-expressions-with-leex-and-yecc-and-reducing-their-syntax-tree#1

**Comment by OleMchls** [comment]
🎉 thanks, also as you did this talk already I'm going to close this
