### ISSUE TITLE
Porting a simple library using Protocols and Code Generation

### ISSUE THREAD

**Issue by OleMchls** [hh-ex/planning#3]
by Julius @h4cc

**Comment by h4cc** [comment]
Topic would we a very simple library mostly using simple string manipulation.
Could be a good introduction for beginners with basic elixir coding.
Also some more advanced topics/ideas like code generation and protocols could be shown.

Time: 20-30 Minutes
Medium: Slides via Beamer

**Comment by h4cc** [comment]
Slides can be found here: https://github.com/h4cc/porting-slugger-library-to-elixir-presentation

**Comment by OleMchls** [comment]
Awesome, thanks @h4cc so I'm going to close this one here, and thanks for your talk!
