### ISSUE TITLE
February Edition - 1st Anniversary

### ISSUE THREAD

**Issue by OleMchls** [hh-ex/planning#30]
# Plan
- [x] Create meetup.com event
- [x] Agenda
- [x] prepare katas if applicable
- [x] Location
- [x] Announce meetup.com event (triggers mail)
# Execute
- **Date:** February 28th
- **Location:** Sabio with @dszam

Agenda:
- 18:00 Open the doors 
- 18:30 Welcome 
- Meet our guest: Tobias Pfeiffer 
- The hh.ex vindinium challenge: half-time report
- Talk: How fast is it really? Benchmarking in practice 
- Open Source together: benchee 
- Hang out and have beers, coke, mate or whats-o-ever 🍻

**Comment by OleMchls** [comment]
We need something special for our first birthday 🎉 Ideas welcome!

**Comment by OleMchls** [comment]
Just created the event at meetup.com. Also #37 is set! So we will have @pragtob :tada:

**Comment by OleMchls** [comment]
IIRC @dszam will host us :)

**Comment by OleMchls** [comment]
Updated location and agenda

**Comment by OleMchls** [comment]
Going to announce the event 🎉 #intime

**Comment by h4cc** [comment]
Screenshot to explain vindinium for the half-time report: 
https://s3.amazonaws.com/poly-screenshots.angel.co/Project/a0/120663/73d89cbf74dde0cacf22233ec6dc6a79-original.png

**Comment by h4cc** [comment]
For the vindinium "half-time report" some extraordinary hackers like @narrowtux could tell us something about their progress and findings.

**Comment by OleMchls** [comment]
I think I will introduce the project / idea again to every one. Ask for some hands to show who's participating and announce the tournament for march. Also I'd love to invite everyone who has something to show, to come on stage and show quickly what they got.

**Comment by OleMchls** [comment]
We had no cake :( But a great meetup, thanks to everyone who participated
