### ISSUE TITLE
March edition

### ISSUE THREAD

**Issue by OleMchls** [hh-ex/planning#31]
# Plan
- [x] Create meetup.com event
- [x] Agenda
- [ ] prepare katas if applicable
- [x] Location
- [x] Announce meetup.com event (triggers mail)
# Execute
- **Date:** March 28th
- **Location:** Awesome Venue

Agenda:
- 18:00 Open the doors 
- 18:30 Welcome 
- ...
- Hang out and have beers, coke, mate or whats-o-ever 🍻

**Comment by h4cc** [comment]
How about a vindinium competition?

**Comment by h4cc** [comment]
The private vindium server is running. My bot is ready.

Anybody else wants to have a little competition?

**Comment by narrowtux** [comment]
Can you post the URL here?

**Comment by OleMchls** [comment]
Yeah, we totally want to do that Vindiuium tournament. I want to get all participants on stage, and let the bots fight on screen. And contesters explain / w/o screen share what strategy their bots use.

**Comment by OleMchls** [comment]
I wonder if we have any talk at hand 🤔

**Comment by OleMchls** [comment]
I've found the following proposals:

- #19 by @BjRo
- #13 by @domenicolino
- #8 by @markschmidt 

Anyone of you feels ready to do something on stage?

**Comment by OleMchls** [comment]
If from the "older" proposals no one wants to take stage, @h4cc you'd want to do something about writing that bot in elixir?

**Comment by OleMchls** [comment]
We also need a location :D I'd love to give ePages another visit, the location would work great for the tournament. @erikmueller ?

**Comment by erikmueller** [comment]
I can check the avail but could be that I can't confirm until next week.

**Comment by OleMchls** [comment]
@erikmueller cool! Can you confirm on Monday, because the automated announcement happens one week prior the the event :D

**Comment by OleMchls** [comment]
I also just created the meetup event: https://www.meetup.com/Elixir-Hamburg/events/238421135/

**Comment by erikmueller** [comment]
@nesQuick Yes will do my best to confirm before but worst case, monday will be latest

**Comment by OleMchls** [comment]
@erikmueller Thanks a bunch! ✨

**Comment by markschmidt** [comment]
@nesQuick sorry, don't count on me in the next time. OutOfSpareTimeException (╯°□°）╯︵ [_]||

**Comment by BjRo** [comment]
@nesQuick same for me. Busy with my current project. Plus, I've been a bit `elixir` abscent in the last weeks (since my current proj is `Scala` based) :-(

**Comment by erikmueller** [comment]
Btw depending on how long @h4cc "botting" takes: I started a small blog engine with `Phoenix` `Agent` and `GenServer` where I'd love to have s/o offer criticism on some parts. If anyone is interested in hearing...

**Comment by OleMchls** [comment]
@erikmueller I'd love to hear that! Let's do that, any bot stuff can be moved to a later meetup as well :) Could you sum up your stuff in two sentences, so I can add it to the website?

**Comment by erikmueller** [comment]
The starting point is a bare phoenix server w/o `Ecto`. I have 2 workers, an `Agent` and a `GenServer`. The Agent reads a directory, of markdown files, turns them into a list of `%Post{}` structs and provides some calls to get and update them. The GenServer acts as a file watcher calling the Agent's state manipulation methods whenever an `md` file changes. Basically a poor mans blog engine with live compiling. 

https://github.com/erikmueller/jelly_shot

**Comment by erikmueller** [comment]
@nesQuick 👌  room's booked for us. Holstenwall as last time.

**Comment by OleMchls** [comment]
Sweet! Thanks :)

**Comment by OleMchls** [comment]
Announced the meetup! :)

**Comment by h4cc** [comment]
Another tweety tweet: https://twitter.com/HamburgEx/status/846590954337439745

**Comment by h4cc** [comment]
@erikmueller Will we have good wifi at epages to play vindinum at out server?

**Comment by OleMchls** [comment]
Worked like a charm last time ;)

**Comment by erikmueller** [comment]
as @nesQuick said it should be no different from last time but I have a chat with IT anyway. @h4cc  are you planning to have the server locally? Because this could be an issue since I'm not sure if devices can discover each other in the guest Wifi.

**Comment by h4cc** [comment]
@erikmueller Thanks for the hint, no the server will be in the internet. 

I also resetted the database for our vindinium instance: http://vindinium.elixir.hamburg/

**Comment by h4cc** [comment]
@erikmueller Ole cant not attend, i will try to do his part today. I will be at ePages at 17:20/30, i know you have prepared everything perfectly like you did last time ;)

**Comment by erikmueller** [comment]
@h4cc thanks for jumping in, I'll do my best ;)

**Comment by OleMchls** [comment]
Big thanks to @h4cc and @erikmueller this one is ✅
