### ISSUE TITLE
Format: Write vindinium AI

### ISSUE THREAD

**Issue by OleMchls** [hh-ex/planning#35]
I just discovered vindinium and also just wrote the elixir client for it: https://github.com/nesQuick/vindinium-elixir-starter

Maybe we could go and write some nice AIs in Elixir all together 🎉

**Comment by OleMchls** [comment]
I'd love to get some feedback on this idea!

**Comment by zweizeichen** [comment]
Sounds like a whole lot of fun! I like that idea a lot!

**Comment by h4cc** [comment]
Cool thing! My first idea would be a bot that will try to detect one of the 6 public maps and optimize this way ;)
https://github.com/ornicar/vindinium/blob/master/app/Maps.scala

**Comment by OleMchls** [comment]
✅
