### ISSUE TITLE
Proposal: How fast is it really? Benchmarking in practice

### ISSUE THREAD

**Issue by PragTob** [hh-ex/planning#37]
I gave this talk at Elixirlive and it was generally well received. It's general benchmarking advice intertwined with samples and benchee sample code (I'm the maintainer of [benchee](https://github.com/PragTob/benchee) - a benchmarking library for Elixir).

Would love to come to Hamburg some time, give the talk and then maybe work on benchee issues or do some collective benchmarking discovering interesting stuff :)

## Abstract

“What’s the fastest way of doing this?” - you might ask yourself during development. Sure, you can guess what’s fastest or how long something will take, but do you know? How long does it take to sort a list of 1 Million elements? Are tail-recursive functions always the fastest?

Benchmarking is here to answer these questions. However, there are many pitfalls around setting up a good benchmark and interpreting the results. This talk will guide you through, introduce best practices and show you some surprising benchmarking results along the way.

**Comment by OleMchls** [comment]
Thanks @PragTob – I'd love to plan this for February 28th, would this work for you? We could make it a similar event as we did with Credo: https://github.com/hh-ex/planning/issues/28#issuecomment-251518683 & https://github.com/hh-ex/planning/issues/20

**Comment by PragTob** [comment]
Oi! Sorry forgot to reply here :( I think that sounds good, just gotta check with my boss if it's fine for me to be remote/tardish or take a day off (started a new job) - but usually there are no problems. Also check if I can crush with some friends in Hamburg or take the last train back. I'll add a blocker to my calendar either way :)

**Comment by OleMchls** [comment]
Sounds great. Let me know when you know for sure, so I will add this to #30

**Comment by PragTob** [comment]
@nesQuick all sustems green, ready to launch. How long are the meetups usually? (Trying to figure out if I should aim for last ICE back home, which is rather early or hit some friends up for couch opportunities)

**Comment by OleMchls** [comment]
Well, on this edition this obviously depend on you. But as we do start kind of early for a UG ~18:30 we are often done with the programming around 21:30/22:00 and hang out for beers and drinks for about a hours more. Hope this helps

**Comment by OleMchls** [comment]
Done already. Thanks @PragTob for stepping over :)
