### ISSUE TITLE
Septemburgers

### ISSUE THREAD

**Issue by OleMchls** [hh-ex/planning#41]
# Plan
- [x] Create meetup.com event
- [x] Agenda
- [ ] ~~prepare katas if applicable~~
- [x] Location
- [x] Announce meetup.com event (triggers mail)

# Execute
- **Date:** Month 26th
- **Location:** Alphacoders

Agenda:
- 18:00 Open the doors 
- 18:30 Fire up the BBQ 
- 19:00 Start eating 🍔
- Hang out and have beers, coke, mate or whats-o-ever 🍻

**Comment by OleMchls** [comment]
Last years description

> We want to celebrate with you! 🎉 Our 7th meet up, Elixir Conf US, and our awesome Hamburg elixir community! That is why we will do a special meet up for September. And what else should the Hamburg elixir user group do other then grabbing delicious hamburgers and some ice cooled drinks with you! Hanging our together and enjoy the awesome Hamburg Elixir community.
In order to improve planning (reduce no show rate) we are collecting 5 Euro when you sign up for the burgers, but here is the deal: When you show up at the meet up we will return it to you (cash) so you can grab yourself a beer or what ever you prefer to drink.

**Comment by OleMchls** [comment]
For this time we managed to get alphacoders as a sponsor. So we can enjoy heir rooftop terrace while grilling our own burgers 🍔

**Comment by OleMchls** [comment]
Created the event, and announced it right away 🎉

**Comment by OleMchls** [comment]
@h4cc You're taking care of 🐦 ?

**Comment by OleMchls** [comment]
As we have plenty of time, I'd like to tweet about it multiple times :)

**Comment by h4cc** [comment]
I will take care of the bird :+1:

**Comment by h4cc** [comment]
Will there be vegetarian burgers too?

**Comment by OleMchls** [comment]
We will get a few veggie patties as well. We plan for a Burger bar, so I should be able to handle these as well. IIRC there was a dietary requirement questionnaire when signing up.

**Comment by OleMchls** [comment]
We had a blast, and I was able to collect some awesome contributions to our next meetups:

@arvidkahl Talk Oktober
@jh2 Talk November 
@dszam Talk Not Learning Elixir (I need a proposed month here, pls)
@dixel Kata November 
@erikmueller HandsOn Node to Nerves Januar

**Comment by OleMchls** [comment]
That makes Septemburgers a wrap. Thanks for making it happen!
