### ISSUE TITLE
Basics of Metaprogramming in Elixir

### ISSUE THREAD

**Issue by OleMchls** [hh-ex/planning#5]
by Björn @BjRo

**Comment by LydG** [comment]
We thought it would be cool to do this in April when we are at Xing? Sound that good to you @BjRo?

**Comment by BjRo** [comment]
Yes, absolutely fine with me. After thinking a bit about it yesterday, I would probably revise the topic slightly though. 

What do you think about "Basics of Metaprogramming in Elixir"?

We just finished working on the DSL code I mentioned yesterday and I got the impression that maybe for the starters in the group, it might be a little bit early for such a topic. (and my original idea is more a kind of a Metaprogramming part 2 or even part 3 topic).

The goal of the new talk would be explain 
- the AST
- quoting / unquoting
- and the role of macros in elixir

No pre-knowledge required. All in code, no slides. Not more than 30 minutes. If the group is interested, we can then do a sequel (or I just show the DSL code over a beer :-))

Thoughts?

**Comment by KlausTrainer** [comment]
:+1:

**Comment by erikmueller** [comment]
:+1: I'd really love to get some insights into this macro stuff (and the beer).

**Comment by zweizeichen** [comment]
Seems reasonable to start with the basics - maybe there could be a nice kata for practicing afterwards? Cool topic! :+1:

**Comment by OleMchls** [comment]
@BjRo sounds awesome! :heart: I adjusted the issue title and filled in the details in #6 :tada: 

I like the idea to have a **related** programming _thingy_ afterwards. @LydG ideas / opinions?
