### ISSUE TITLE
Project proposal: Phoenix boilerplate/starter

### ISSUE THREAD

**Issue by jh2** [hh-ex/planning#51]
As discussed at the last meetup there is a big hurdle when starting a new Phoenix-based project: You have to do a lot of things from scratch, especially authentication. So I propose we build a boilerplate/starter project (these are very common in javascript-world) that you just have to clone, adjust some configuration, run and it gives you a phoenix project with out-of-the-box:
- authentication (account creation, login, password forgot, etc)
- authorization (who can access what with example restricted routes)
- roles (at least two: admin and regular users)
- profile edit pages where users can change their passwords, etc
- admin page to administer user accounts

maybe:
- social logins
- a branch for SPAs with brunch replaced by react + webpack
- distillery release build
- whatever else you might think is important

Might be a bit optimistic but I think we can discuss library choices and write this in a few meetups. What do you think?

**Comment by dszam** [comment]
sounds like a pretty nice idee for me.
I'd really like to do this kind of project.

**Comment by OleMchls** [comment]
@jh2 I thinks that's pretty cool, too! I'm 100% down for this. Would you moderate this activity? We've no agenda for the May meetup. So I could see this activity there. Maybe as with the April meetup have it as a single agenda item so we can put more time towards that.

I'd see you start with explaining the problem, showing other boilerplates for other languages for a few minutes at the beginning and then dive deep into coding. Or what did you have in mind?

**Comment by jh2** [comment]
Yes, pretty much what I had in mind. I can moderate it, sure. May is fine, too 👍

**Comment by erikmueller** [comment]
> a branch for SPAs with brunch replaced by react + webpack

Awesome. I don't know how often I replaced brunch with webpack... I think this is not only relevant for react-based projects. Especially with the new webpack zero-conf release it should be as simple but more powerful (ES6 transpiling & friends) than brunch 👍  

... and not to mention webpack widely used (concerning tutorials, examples, etc...)

**Comment by OleMchls** [comment]
Sweet! @jh2 please be prepared for the May meetup! I'll update #48 and then we are set for May 🎉 Maybe you want to provide me with a little description of what you want to do?

**Comment by OleMchls** [comment]
We did this in May 2018
