### ISSUE TITLE
Septemburgers 2018

### ISSUE THREAD

**Issue by OleMchls** [hh-ex/planning#55]
# Plan
- [x] Agenda (🍔)
- [x] prepare katas if applicable
- [x] Location Alphacoders
- [x] Announce meetup.com event (triggers mail)
- [ ] Promote on Twitter

# Execute
- **Date:** September 25th
- **Location:** Alphacoders

Agenda:
- 18:00 Open the doors 
- 18:30 Welcome 
- BURGERS!
- Hang out and have beers, coke, mate or whats-o-ever 🍻

**Comment by OleMchls** [comment]
I've created and adjusted the meetup event.

**Comment by narrowtux** [comment]
I can bring a scale and a patty press 
![image](https://user-images.githubusercontent.com/616791/42722903-67ef4200-8754-11e8-9398-777069528f6c.png)

**Comment by OleMchls** [comment]
@narrowtux Weee! Do you also have a ingrediants list for us when we go shopping? Last time we realized no ones of us were _really_ into home made burgers :D

**Comment by narrowtux** [comment]
I have the [Bob's Burgers recipe book](https://www.amazon.de/Bobs-Burgers-Burger-Book-Recipes/dp/0789331144/ref=sr_1_1?ie=UTF8&qid=1531771548&sr=8-1&keywords=bob%27s+burger+burger+book). I'll select a few recipes so people can try different things.

**Comment by OleMchls** [comment]
Alright. Just share with us what we need to buy! :)

**Comment by narrowtux** [comment]
I'll get back to that in august.

**Comment by OleMchls** [comment]
👍

**Comment by erikmueller** [comment]
@narrowtux the recipes look awesome 👍 I could also bring a burger press with cheese insertion ability 😄

**Comment by OleMchls** [comment]
Announced on Meetup. That gives people enough time to plan for it.

**Comment by narrowtux** [comment]
Ok! I have 3 options, even one veggie one!

I copied the ingredients for convenience, they're scaled for 4 burgers

## New Baconings Burger
![img_5514](https://user-images.githubusercontent.com/616791/45929053-ce0a4780-bf4c-11e8-8bb4-379038b30d70.JPG)
Ignore the milk and egg ingredients, those are for the fries which we most likely won't have.

 * ~200g Bacon
 * Beef for 4 patties
 * 4 Burger buns
 * Lettuce
 * Tomatos
 * Onions

## The Final Kraut Down Burger
![img_5515](https://user-images.githubusercontent.com/616791/45929054-d19dce80-bf4c-11e8-9a52-cc85d4c2e995.JPG)

 * Butter
 *  Onions
 * 1 can Sauerkraut 
 * Swiss cheese, 4 slices
 * Dijon mustard
 * 4 burger buns
 * Beef for 4 patties

## Mediterr'-Ain't Misbehavin' Burger (Veggie)
![img_5516](https://user-images.githubusercontent.com/616791/45928939-73bcb700-bf4b-11e8-8fc4-4005bb95cdc8.JPG)

 * 1 large eggplant
 * 1 can chickpeas
 * Tzatziki (I'll prepare at home tomorrow)
 * Arugula (Rucola)

## Meat!

For the meat I'd recommend something between 120 and 180g per patty.
