### ISSUE TITLE
Venue in Hafencity

### ISSUE THREAD

**Issue by TamyRibeiro** [hh-ex/planning#65]
Hi there,
Wunder is selecting an exclusive list of Tech Meetups to be hosted for free in our stunning office in Hafencity, providing the venue, equipment, free drinks, snacks and perks to your community. Let's talk about it? 

Here is the concept: 

https://docs.google.com/presentation/d/1cgch4Je7szEgCsJ1PG80WuP69z9WpqAh1U2qyOGn-bU/edit?usp=sharing

Cheers!

**Comment by OleMchls** [comment]
Hey @TamyRibeiro we always appreciate new venues. So thanks for the offer. Our next meetup that is not yet assigned to a venue is #58 would that day work for you? That one _may_ be a special version: #64 /cc @jh2

**Comment by TamyRibeiro** [comment]
Hi Ole,

Sounds good. Let's confirm this date.

Please let me know when can we discuss details.

Best,




Hi, I'm Tamy Ribeiro
Brand Partnerships Lead at Wunder Mobility <http://www.wunder.org/>

ᐧ

**Comment by OleMchls** [comment]
@TamyRibeiro we can discuss everything in #58 
The date for the January meetup is January 29th 2019.

**Comment by bruno-azenha** [comment]
@OleMchls I believe we can close this one. ;)

**Comment by OleMchls** [comment]
👍 thanks @bruno-azenha
