### ISSUE TITLE
Elixir Coderetreat - May

### ISSUE THREAD

**Issue by IvanRublev** [hh-ex/planning#67]
### Let's extend Kata to a full day Coderetreat event!

The Coderetreat is a full day practice focused on the fundamentals of software development - software design, clean code, refactorings (https://www.coderetreat.org/).

The general idea is to solve simple problems with Elixir to have fun! 🎉

The event takes place in the first half of May.
We will add more information here and in the meetup group.

Thanks for the support to @OleMchls @bruno-azenha and the community 👍 

If you have an Idea, question, or excitement then, please, comment here or email me at ivan@ivanrublev.me .

Best Regards!

**Comment by OleMchls** [comment]
@IvanRublev thanks for following up on this here. As said, I will help you putting this up within the meetup group? I will create a scaffold event and make you the organizer.

**Comment by bruno-azenha** [comment]
I'm really excited about this, and happy to say that we at Wunder Mobility would love to host it!
I've already talked with our events team and they are on board with the idea as well

I would imagine that being a full day of activities, it would probably be on a weekend, right?
How should we decide on a specific date?

**Comment by IvanRublev** [comment]
Yes, it’d be great to have a full day event of 4 - 5 coding sessions with
retros. It can be a Saturday. I’m out of the city at 4th of May, and
available all other days. The 10th of May suits me well.
@janderit what’s the avaliability of the facilitator you have on mind?

**Comment by OleMchls** [comment]
I've created https://www.meetup.com/Elixir-Hamburg/events/260145260/ for you to use. Please feel free to edit as you see fit :) Also once more detailes are set, I think it makes sense to e-mail the entire group via meetup.

**Comment by OleMchls** [comment]
> I've created https://www.meetup.com/Elixir-Hamburg/events/260145260/ for you to use. Please feel free to edit as you see fit :) Also once more detailes are set, I think it makes sense to e-mail the entire group via meetup.

@IvanRublev I hope I equipped you with all rights necessary to do so

**Comment by IvanRublev** [comment]
Great thanks @OleMchls  I can edit the event 👍

**Comment by janderit** [comment]
@ivanrublev I will reach out and ask him this weekend.

**Comment by IvanRublev** [comment]
Okay, Organizers and Supporters, @OleMchls, @bruno-azenha, @janderit it's time to make a kickoff video meeting on Friday 5th. Let Google Calendar and Hangouts help us.
* Please, email me from your google account till the 4th of April.
* I add you to the meeting. 
* Then you can add others (@bruno-azenha, please, add your events team), and we agree call time. 
* We have a call on Friday via Hangouts.

UPD: Participants count (4) 
Great thanks for meeting!

**Comment by OleMchls** [comment]
Thanks @IvanRublev and @bruno-azenha for putting this together. 

I assume there is no more followup needed here, thus closing the issue.
