### ISSUE TITLE
"War story" - Bring it to production and keep it up

### ISSUE THREAD

**Issue by markschmidt** [hh-ex/planning#8]
I'm not really sure how useful this is to others, because most of it seems pretty obvious to me in retrospective and some of the problems/solutions are coupled (but probably not unique) to our infrastrucure.

However, I could talk about the issues we faced bringing it to production and keeping it up. Topics I would cover:
- deployment
- logging / monitoring
- profiling / finding bottlenecks
- Lessons learned
  - supervisor hierarchies
  - errors the compiler doesn't catch
  - beware when not using OTP

**Comment by OleMchls** [comment]
I'd love to hear this. A bit about compiling would also be nice :)

**Comment by zweizeichen** [comment]
Yeah and testing/CI/CD if you have made any special experiences ;)

**Comment by KlausTrainer** [comment]
:+1:

**Comment by lukad** [comment]
I would love to hear a talk about this as well.
:+1:

**Comment by OleMchls** [comment]
@markschmidt would you be in to give this at this october edition? #27

**Comment by markschmidt** [comment]
@nesQuick sorry, but I won't find time for that currently 😫

**Comment by OleMchls** [comment]
alright, so we delay it to other meetup :)

**Comment by OleMchls** [comment]
While still a great proposal, I consider the lack of activity as a withdrawal of the proposal.
