### ISSUE TITLE
More Lightning Talks

### ISSUE THREAD

**Issue by h4cc** [hh-ex/planning#83]
## The Idea

Providing a base for lightning talks next to normal talks/kata format.

> Suggestion from the Glühwein & waffels meetup

## Why?

Offering people a way to bring in their ideas and content.

## What I need from the orga

Promoting Lightning talks in planing with meetup/twitter description or github issues.

> This is a suggestion from the Glühwein & waffels meetup

**Comment by OleMchls** [comment]
I also update the meetup.com description with the changes from 4565cc6
