### ISSUE TITLE
More code katas

### ISSUE THREAD

**Issue by h4cc** [hh-ex/planning#84]
## The Idea

Encourage coding katas, also smaller ones.

Tell in meetup description / tweet to bring you notebook for coding the kata.

## Why?

More interaction between members and ideas about solving problems.

## What I need from the orga

Provide a howto for katas.
Ask / inform in meetup text / tweet for kata ideas.

> This is a suggestion from the Glühwein & waffels meetup

**Comment by OleMchls** [comment]
I did a complete overhaul of the `format` ticket https://github.com/hh-ex/planning/issues/15 so hopefully, the instructions are now clear(er)
