### ISSUE TITLE
June 2021 Edition

### ISSUE THREAD

**Issue by IvanRublev** [hh-ex/planning#91]
# Plan
- [x] Agenda
- [x] Location
- [x] Announce meetup.com event (triggers mail)
- [x] Promote on Twitter

# Execute
- **Organizer**: Ivan
- **Date:** June 22nd
- **Location:** Online in Jitsi meet (https://meet.jit.si/)

Agenda (upd):
- 19:00 Welcome 
- 19:30 Domo - model a business domain with type-safe structs and field type preconditions
- 20:00 Lightning talks
- Hang out and have beers, coke, mate, anything you bring with you to the online meeting 🍻

**Comment by IvanRublev** [comment]
Folks, we haven't met for ages. I've just released a new version of Domo library that's about type-safe structs. It'd be cool to show it to you to get your feedback about it 😄

**Comment by OleMchls** [comment]
@IvanRublev  I take you would take the organiser part for this meetup? If so I'll happily get you all access on meetup.com to get everything started.

**Comment by OleMchls** [comment]
I'll happily chime in with an lightning talk :)

**Comment by OleMchls** [comment]
@IvanRublev  I've created https://www.meetup.com/Elixir-Hamburg/events/278571735/ you have admin rights on that one. It needs a quick description, you can copy and adjust It from past events or https://github.com/hh-ex/planning/blob/master/meetup-template.md

Thanks for kicking this off 💪

**Comment by IvanRublev** [comment]
@OleMchls thanks for creating the event. Super cool to have the lightning talk from you.
Can make the description and announcement 🤘

**Comment by IvanRublev** [comment]
Made announcement on  erlef.org 😊

![Screen Shot 2021-06-05 at 15 47 13](https://user-images.githubusercontent.com/5757941/120893994-599d6700-c616-11eb-9943-114bdf9bc40e.png)

**Comment by IvanRublev** [comment]
@OleMchls is now a bad time for promo on Twitter? 😀

**Comment by OleMchls** [comment]
> @OleMchls is now a bad time for promo on Twitter? 😀

Sure why not. I'll pass you the credentials via DM
