### ISSUE TITLE
September Edition

### ISSUE THREAD

**Issue by OleMchls** [hh-ex/planning#93]
# Plan
- [ ] Agenda
- [ ] prepare katas if applicable
- [ ] Location
- [ ] Announce meetup.com event (triggers mail)
- [ ] Promote on Twitter

# Execute
- **Organizer**: Ole || Julius || Morith
- **Date:** September 27th
- **Location:** Awesome Venue

Agenda:
- 18:00 Open the doors 
- 18:30 Welcome 
- ...
- Hang out and have beers, coke, mate or whats-o-ever 🍻

**Comment by OleMchls** [comment]
First things first, we do need a venue and some sort of agenda. Any takers?

**Comment by narrowtux** [comment]
I've been really sick these past 2 weeks, sorry I couldn't be of more help.
